### ISSUE TITLE
WDA issue

### ISSUE THREAD

**Issue by Chaithra-Menon** [nanoscopic/ios_remote_provider#12] opened 2021-03-26 12:06 UTC
Installed vidtest and all the steps. On running main run, it was throwing an error here:
```id = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
INFO[0003] Process start - wda                           binary=xcodebuild proc=wda testrun=repos/WebDriverAgent/build/Build/Products/WebDriverAgentRunner_iphoneos14.4-arm64-armv7.xctestrun type=proc_start
INFO[0003] Process start - backupVideo                   binary=bin/iosif id=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX port=8105 proc=backupVideo type=proc_start
INFO[0003] listening on tcp://127.0.0.1:8105             proc=backupVideo
listening on tcp://127.0.0.1:8105
Got connection to port
panic: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:51301->127.0.0.1:8102: read: connection reset by peer

goroutine 39 [running]:
main.(*WDA).create_session(0xc00028e0e0, 0x0, 0x0, 0xc0003301c0, 0xc000180700)
	ios_remote_provider/wda.go:202 +0x3ab
main.(*WDA).ensureSession(0xc00028e0e0)
	ios_remote_provider/wda.go:161 +0x3a
main.(*Device).enableVideo(0xc000340000)
	ios_remote_provider/device.go:236 +0x74
main.(*Device).startProcs(0xc000340000)
	ios_remote_provider/device.go:205 +0xd4
main.(*DeviceTracker).onDeviceConnect1(0xc0000cbdb0, 0x442f600, 0xc00014a6c0, 0xc00018add0)
	ios_remote_provider/device_tracker.go:100 +0x398
main.NewDeviceTracker.func1(0x442f600, 0xc00014a6c0, 0xc0001162a0, 0x28)
	ios_remote_provider/device_tracker.go:42 +0x3e
main.(*IIFBridge).OnConnect(0xc0000be980, 0xc0001162a0, 0x28, 0xc000118c00, 0x6, 0xc0000cd5e0)
	ios_remote_provider/bridge_iif.go:86 +0xc8
main.(*IIFBridge).startDetect.func2(0xc0001b8230, 0x4e, 0xc0000cd5e0)
	ios_remote_provider/bridge_iif.go:62 +0x29a
main.proc_generic.func1(0xc0000cd5e0, 0xc00009bd70, 0xc00022e380, 0xc00009bc80, 0xc00009bd40, 0xc000202300, 0xc0000e7510, 0x0, 0x0)
	ios_remote_provider/proc_generic.go:190 +0xe4f
created by main.proc_generic
	ios_remote_provider/proc_generic.go:105 +0x626```

**Comment by asmiou** [comment] 2021-04-22 22:04
Hi everyone, I also have the same error. Someone would have a solution please.
@nanoscopic

**Comment by sai-tirunagiri** [comment] 2021-04-28 18:46
did you try starting the vidtest app?

before you start the provider, you should start brodcast from the vidtest app on the device.

**Comment by AdamDuongIt** [comment] 2021-05-17 04:39
I got same behavior but seem the log said different thing.
Noted that I already starting the vidtest app, crash happen when I try to control the screen via web (localhost:8080).

`Could not parse:[[on,"","eplayd[4310] <Notice",` [INFO] -[RPScreenCaptureManagerIOS screenCaptureController:didReceiveSampleBuffer:transformFlags:]:104 screen sampled at window size width:828 heigth:1792 transformFlags 0`]]
panic: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:54946->127.0.0.1:8102: read: connection reset by peer

goroutine 225 [running]:
main.(*WDA).create_session(0xc0000b61c0, 0x0, 0x0, 0x30, 0x43950e0)
        /Users/gameloft/Documents/workspace/ios_remote_provider/wda.go:120 +0x3ab
main.(*WDA).ensureSession(0xc0000b61c0)
        /Users/gameloft/Documents/workspace/ios_remote_provider/wda.go:79 +0x3a
main.(*WDA).sessionCall(0xc0000b61c0, 0x43b6e99, 0x12, 0xc00024e1a0, 0x19c, 0xc00024e1a0, 0x19c)
        /Users/gameloft/Documents/workspace/ios_remote_provider/wda.go:159 +0x456
main.(*WDA).swipe(0xc0000b61c0, 0x15c, 0x23a, 0x59, 0x239)
        /Users/gameloft/Documents/workspace/ios_remote_provider/wda.go:301 +0x2a9
main.(*Device).swipe(...)
        /Users/gameloft/Documents/workspace/ios_remote_provider/device.go:349
main.(*ControlFloor).openWebsocket.func6(0xc0000b0000, 0xc0000220e0, 0x19, 0x15c, 0x23a, 0x59, 0x239)
        /Users/gameloft/Documents/workspace/ios_remote_provider/controlfloor.go:285 +0xa7
created by main.(*ControlFloor).openWebsocket
        /Users/gameloft/Documents/workspace/ios_remote_provider/controlfloor.go:282 +0x9d8`

**Comment by nanoscopic** [comment] 2021-05-24 11:11
@Chaithra-Menon @asmiou  There have been new options added to allow one to specify the method used for accessing the control center in order to start the video app automatically. It is, though, not yet documented. You can see the parsing code for the config here for the moment: https://github.com/nanoscopic/ios_remote_provider/blob/main/config.go#L85

Once the proper method is chosen ( it defaults to bottomup and is likely topdown for your device... ), then this issue should go away.

As @sai-tirunagiri says, starting the video app manually first is a work around.

I am going to add a video diagnostics command as well to help understand issues of this type, as this is a very common problem for users and the errors in no way make it clear currently what is going on when there is an issue.

**Comment by nanoscopic** [comment] 2021-05-24 11:19
Looks like a duplicate of #11

**Comment by nanoscopic** [comment] 2021-06-18 03:45
This has been corrected.

**Closed by nanoscopic** 2021-06-18 03:45 UTC
