### ISSUE TITLE
remote provider breaks on keys event

### ISSUE THREAD

**Issue by sai-tirunagiri** [nanoscopic/ios_remote_provider#20] opened 2021-05-28 18:58 UTC
Hi,

When executing the pressbutton event, I have observed the remote provider breaks with the following stacktrace. and also it happens on keyPress.

```
goroutine 1384 [running]:
main.resp_to_str(0x0, 0xc0004c4740, 0xc0009e4400)
	/Users/macmini1_df_uk/Documents/ios_remote_provider_latest/ios_remote_provider/wda.go:86 +0x26
main.resp_to_val(0x0, 0xc0009f4000, 0x52)
	/Users/macmini1_df_uk/Documents/ios_remote_provider_latest/ios_remote_provider/wda.go:96 +0x2f
main.(*WDA).sessionCall(0xc00031c230, 0x43aef0d, 0x10, 0xc0000e8060, 0x1d, 0xc000488040, 0x38)
	/Users/macmini1_df_uk/Documents/ios_remote_provider_latest/ios_remote_provider/wda.go:181 +0x1e5
main.(*WDA).pressControlButton(0xc00031c230, 0xc000316178, 0x8)
	/Users/macmini1_df_uk/Documents/ios_remote_provider_latest/ios_remote_provider/wda.go:296 +0x173
main.(*Device).pressControlButton(...)
	/Users/macmini1_df_uk/Documents/ios_remote_provider_latest/ios_remote_provider/device.go:336
main.(*ControlFloor).openWebsocket.func8(0xc0000d4200, 0xc0000e8040, 0x19, 0xc000316178, 0x8)
	/Users/macmini1_df_uk/Documents/ios_remote_provider_latest/ios_remote_provider/controlfloor.go:303 +0x93
created by main.(*ControlFloor).openWebsocket
	/Users/macmini1_df_uk/Documents/ios_remote_provider_latest/ios_remote_provider/controlfloor.go:300 +0x798
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x42f9146]
```

Any help on the above.

Thanks.

**Comment by nanoscopic** [comment] 2021-05-28 19:18
I've seen others mention this result as well. My initial thought on this was that it is due to WDA not actually running correctly. Could you verify that WDA is up and running properly ( got to http://localhost:8102/status in browser ) ?

The weird thing is that the calls to WDA are returning something, just whatever it is is an invalid valid that is causing the parsing of it to crash ( hence rest_to_str failing ). I'll need to alter the code to output what is returned when a bad value is received back to be able to diagnose this, as I don't know what WDA is returning for you that breaks it.

**Comment by chewbacca70** [comment] 2021-06-03 17:07
I also Face this issue 😕. Any News on That?
Cheers

**Comment by nanoscopic** [comment] 2021-06-07 07:45
I've never seen this on any of the devices I've tried. The information above is inadequate to make any determination as to the cause.

You'll need to make the call manually ( either using curl or using https://github.com/nanoscopic/ios_controller ) and report back what WDA is actually returning when the call is made for me to be able to diagnose this.

Please do the following:
1. Start wda using controller `./main wda`
2. Ensure wda is working ( visit http://localhost:8102/status )
3. Create a wda session using curl or ios_controller ( see wda documentation or use ios_controller create_simple_session func )
4. Make the call that is breaking; in this case the code is here: https://github.com/nanoscopic/ios_controller ; that is a call to /session/[session id]/wda/keys . Either make that call manually using curl, or use ios_controller to call it.
5. Report back what happens / if it works or not / what WDA returns from the call.

**Comment by sai-tirunagiri** [comment] 2021-06-15 13:52
@nanoscopic - Here is what I was able to track so far, I cloned the latest code and started typing and this is what I see on ios remote provider

```
Posting to http://127.0.0.1:8102/session/2A08CC24-F23A-44B1-B79E-02A688039A4D/wda/keys
INFO[0083] sending {
        "value": ["v","j","h","h","d","j"]
    }
Posting to http://127.0.0.1:8102/session/2A08CC24-F23A-44B1-B79E-02A688039A4D/wda/keys
Result: {
  "value" : null,
  "sessionId" : "2A08CC24-F23A-44B1-B79E-02A688039A4D"
}
nil response from http request
Result:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x433eead]

goroutine 292 [running]:
main.(*WDA).sessionCall(0xc00035e930, 0x43fb8b0, 0x9, 0xc000022240, 0x3a, 0xc00037c320, 0x42)
	/Users/saiprasadt/Desktop/nanoscopic-15Jun/ios_remote_provider/wda.go:253 +0x28d
main.(*WDA).keys(0xc00035e930, 0xc000022100, 0x8, 0x8)
	/Users/saiprasadt/Desktop/nanoscopic-15Jun/ios_remote_provider/wda.go:347 +0x44c
main.(*Device).keys(0xc0002228c0, 0xc00033e1c0, 0x1f)
	/Users/saiprasadt/Desktop/nanoscopic-15Jun/ios_remote_provider/device.go:389 +0x13f
main.(*ControlFloor).openWebsocket.func7(0xc000220000, 0xc000292030, 0x28, 0xc00033e1c0, 0x1f)
	/Users/saiprasadt/Desktop/nanoscopic-15Jun/ios_remote_provider/controlfloor.go:294 +0x8c
created by main.(*ControlFloor).openWebsocket
	/Users/saiprasadt/Desktop/nanoscopic-15Jun/ios_remote_provider/controlfloor.go:291 +0x7bd
```

tidevice logs
```
[I 210615 19:13:43 _device:841] AppContainer: /private/var/mobile/Containers/Data/Application/356A5D02-2DF9-4C22-B708-D8661A35070B
[I 210615 19:13:43 _device:881] Launch 'com.appium.QyrusRunner.xctrunner' pid: 1710
[I 210615 19:13:43 _device:1014] Test runner ready detected
[I 210615 19:13:43 _device:1006] Start execute test plan with IDE version: 29
[I 210615 19:13:44 _device:917] WebDriverAgent start successfully
[D 210615 19:14:51 _wdaproxy:93] [ada3ad8097e58c7eea8c1821640ccd4cda484bbe] WDA is not response, check again after 10s
[I 210615 19:15:04 _wdaproxy:97] [ada3ad8097e58c7eea8c1821640ccd4cda484bbe] WDA confirmed not running
[I 210615 19:15:04 _wdaproxy:106] [ada3ad8097e58c7eea8c1821640ccd4cda484bbe] WDA keeper stopped
[I 210615 19:15:04 _wdaproxy:145] [ada3ad8097e58c7eea8c1821640ccd4cda484bbe] WDA stopped for the 1st time, running 1.3 minutes
[D 210615 19:15:04 _wdaproxy:118] [ada3ad8097e58c7eea8c1821640ccd4cda484bbe] launch WDA
```

Please give me a workaround for this if any.

**Comment by chewbacca70** [comment] 2021-06-24 06:08
@sai-tirunagiri 
did you sign and push the WDA driver (WebDriverAgentRunner) pulled to /repos after ./make to your connected phone?
This is not written in the Documentation so it could be that you missed to it as I also faced your issue when following the readme.

Cheers
Chubbi

**Comment by sai-tirunagiri** [comment] 2021-06-24 17:28
@chewbacca70 - I was able to solve this issue by adding a nil check. original code - https://github.com/nanoscopic/ios_remote_provider/blob/84133b3c8591a7904315daf06812bbcb9195c11c/wda.go#L258

altered code,
```
if val != nil {
      err = val.Get("error")
}
```

**Comment by nanoscopic** [comment] 2021-06-24 17:45
I finally encountered this error myself randomly today as well. As you say, @sai-tirunagiri , the cause is that WDA just returns null and that isn't handled so it crashes the provider. That change will prevent the crash, but WDA shouldn't fail in that way.

I do have another method of entering text that I will move to, that should be a lot faster and also more stable / not prone to failing the way the current call being used does.

**Comment by nanoscopic** [comment] 2021-06-24 17:47
As another note; the best way to enter text is to avoid WDA entirely and use a raspberry pi nano acting as a usb keyboard. At some point I will write the software and integration to do that and that will be best.

**Comment by sai-tirunagiri** [comment] 2021-06-24 19:39
> As another note; the best way to enter text is to avoid WDA entirely and use a raspberry pi nano acting as a usb keyboard. At some point I will write the software and integration to do that and that will be best.

This would be awesome!

**Comment by sai-tirunagiri** [comment] 2021-07-07 20:09
Hi @nanoscopic , I was so excited to try the new release, yes! it does make the keypress to work smooth but with a problem for me, if I do intensive keypress then suddenly it stops sending keypress requests and when I do ctrl + c on the remote provider I see the following stacktrace.

```
INFO[0261] sending {
          "page": 7,
          "usage": 24,
          "duration": 0.05
        }
INFO[0261] sending {
          "page": 7,
          "usage": 11,
          "duration": 0.05
        }
^CINFO[0265] Shutdown started                              state=begun type=sigterm
INFO[0265] Shutdown proc                                 pid=78832 proc=wda type=shutdown_proc
INFO[0265] Shutdown proc                                 pid=78834 proc=syslogMonitor type=shutdown_proc
INFO[0265] Shutdown proc                                 pid=78833 proc="tunnel_8103->8352_8104->8351" type=shutdown_proc
INFO[0265] Shutdown proc                                 pid=78825 proc=device_trigger type=shutdown_proc
INFO[0265] Shutdown proc                                 pid=78831 proc="tunnel_8102->8100_8106->8150" type=shutdown_proc
INFO[0265] Shutdown proc                                 pid=78830 proc=backupVideo type=shutdown_proc
panic: Post "https://127.0.0.1:8080/provider/devStatus": dial tcp 127.0.0.1:8080: socket: too many open files

goroutine 66 [running]:
main.(*ControlFloor).baseNotify(0xc0000da400, 0x442fd84, 0xe, 0xc000184150, 0x28, 0xc000423700)
	/Users/saiprasadt/Desktop/nanoscopic-6Jul/ios_remote_provider/controlfloor.go:360 +0x393
main.(*ControlFloor).notifyProvisionStopped(...)
	/Users/saiprasadt/Desktop/nanoscopic-6Jul/ios_remote_provider/controlfloor.go:404
main.(*DeviceTracker).shutdown(0xc0000d6460)
	/Users/saiprasadt/Desktop/nanoscopic-6Jul/ios_remote_provider/device_tracker.go:160 +0x43b
main.coro_sigterm.func1(0xc0000b6300, 0xc0000d6460, 0xc000170000)
	/Users/saiprasadt/Desktop/nanoscopic-6Jul/ios_remote_provider/shutdown.go:26 +0x1f6
created by main.coro_sigterm
	/Users/saiprasadt/Desktop/nanoscopic-6Jul/ios_remote_provider/shutdown.go:19 +0xdc
```

Is this because of the ulimit set on macOS, I even tried setting an upper limit but this problem seems to persist.

**Comment by nanoscopic** [comment] 2021-07-07 21:28
Whenever a socket connection is made, there is a timeout for that socket where it will hang around.
My guess is that the way I've written the code for keypress calls, those calls are not reusing the same socket connection to CF. Because they are not being reused, if you make many calls in a short period it will consume available sockets on the machine.

The fix is that I will update the code to reuse the same connection.

**Comment by nanoscopic** [comment] 2021-07-21 04:48
See https://github.com/nanoscopic/ios_remote_provider/issues/39
Closing this as a duplicate of that despite this issue being older.

The key mechanism has changed so above info is no longer relevant.
There remains an issue with many keystrokes causing file descriptor exhaustion, which is being addressed and tracked in issue 39.

**Closed by nanoscopic** 2021-07-21 04:48 UTC
